#!/bin/bash

#SBATCH --job-name=$1             # Job name
#SBATCH --nodes=2                 # Number of nodes
#SBATCH --time=24:00:00           # Time limit hrs:min:sec

# GAMESS env
VERNO=konst
EXEPATH=/home/share/local/sbin/gamess
USERSCR=~/scr
SCR=/scr/k.komarov

# Execute the job
$GMSPATH/rungms $1 $GMSVER 2 >& $1.log &
